
services:
  mssql:
    build:
      context: ./mssql
      dockerfile: Dockerfile
    container_name: mssql_server_dev
    
    env_file: .env

    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASS}
      - MSSQL_SA_PASSWORD=${DB_PASS}
      - MSSQL_PID=Developer
    ports:
      - "1435:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./mssql/backup:/var/opt/mssql/backup
      - ./mssql/init:/init 
      - ./mssql:/mssql  
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"$SA_PASSWORD\" -Q \"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s


  backend:
    build: ./chatbot-toeic-backend
    container_name: chatbot_backend
    restart: always
    env_file: .env 
    environment:
      DB_HOST: mssql
      DB_PORT: 1433
      DB_USER: ${DB_USERNAME}
      DB_PASS: ${DB_PASS}
      DB_NAME: ChatbotToeic
      NODE_ENV: production
    ports:
      - "8080:8080"
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./chatbot-toeic-backend:/app
      - ./frontend/public/Img_project:/Img_project
    command: ["/bin/sh", "wait-for-db.sh", "mssql", "1433", "node", "src/server.js"]

  frontend:
    build:
      context: ./chatbot-toeic-frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    volumes:
      - ./chatbot-toeic-frontend/public/Img_project:/usr/share/nginx/html/Img_project
      - ./chatbot-toeic-frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  sql_data:
    name: chatbot_sql_data
